#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: ''}
- {title: Categories, url: 'categories'}
- {title: Tags, url: 'tags'}
- {title: Contact, url: '#contact'}

#-------------------------------
# Disqus Section
# Must have comments: true to enable comments on post.

disqus: mrdemonwolf-local

#-------------------------------
# About Section

about:
  name: John Doe
  text: Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition
  # Limit of two links
  other-links: true`
  links:
    - {url: 'https://www.example.com/', title: Your site}
    - {url: 'http://www.example.com/', title: Your site}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@example'
  twitter-site: '@example'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# Social Icons and URls
# Icons supported are Twitter, Twitch, Spotify, Github, YouTube, Linkin, and Google Plus
social:
- {name: , icon: 'fa-twitter', color: 'twitter-color', url: 'https://www.twitter.com'}
- {name: , icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv'}
- {name: , icon: 'fa-spotify', color: 'spotify-color', url: 'https://www.spotify.com'}
- {name: , icon: 'fa-github', color: 'github-color', url: 'https://www.github.com'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
# Footer Section

footer-left:
  header: Sitemap
  links:
   - {title: Home, url: ''}
   - {title: Categories, url: 'categories'}
   - {title: Tags, url: 'tags'}
   - {title: Contact, url: '#contact'}

footer-right:
  header: Legal
  links:
   - {url: legal/terms-of-service/ , title: Terms of Service}
   - {url: legal/privacy-statement/ , title: Privacy Statement}

footer-rss:
  url:
  title:

#-------------------------------
