#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}

#-------------------------------
# Disqus Section
# Must have comments: true to enable comments on post.

disqus: mrdemonwolf-local

#-------------------------------
# Hero Section

hero:
  header:
  sub-header:

#-------------------------------
# About Section

about:
  name: John Doe
  text: Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition
  # Limit of two links
  links:
    - {url: 'https://mrdemonwolf.me', title: My personal site}
    - {url: 'https://mrdemonwolf.me', title: My personal site}

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@example'
  twitter-site: '@example'
  type: 'website'
  google-analytics: UA-xxxx-1

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://example.com'}

social-url:
  spotify: https://example.com

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
